name: spmf-env

channels:
  - conda-forge
  - defaults

dependencies:
  - pip==23.3.2
  - python==3.9.*

  - pip:
    - ipykernel==6.20.2
    - autopep8==2.0.0
    - notebook==6.5.2
    - pre-commit==2.21.0
    - flake8==6.1.0
    - isort==5.11.4
    - build==0.10.0
    - twine==4.0.2
    - artifacts-keyring==0.3.2
    - pytest==7.2.2
    - jupytext==1.14.5
    - -r requirements.txt
