name: spmf-env

channels:
  - conda-forge
  - defaults

dependencies:
  - pip==23.3.2
  - python==3.9.*

  - pip:
    - ipykernel==6.29.2
    - autopep8==2.0.4
    - notebook==7.1.0
    - pre-commit==3.6.2
    - flake8==7.0.0
    - isort==5.13.2
    - build==1.0.3
    - twine==5.0.0
    - setuptools==69.1.1
    - wheel==0.42.0
    - pytest==8.0.1
    - jupytext==1.16.1
    - -r requirements.txt
